### ISSUE TITLE
adding columns to the data frame

### ISSUE THREAD

**Issue by mikeatm** [patrickpato/MaterialProject_project#1]
https://github.com/patrickpato/MaterialProject_project/blob/09d95ae47ea6033c2cfca51482b5959811737e84/Materials-Project-Materials-Miner.ipynb#L162

this cell is attempting to add columns to the data frame,  but clearly this is not how it should be done, look at the documentation for  dataframe and see how to do that right, this is not adding columns to each of the rows, but adding columns to the same row over and over, and leaving the other rows with NaNs on those rows.  to do this correctly, ensure  you add columns to all the rows at the same time, by gathering all the  columns , then adding them all at once.  [see this example ](https://www.geeksforgeeks.org/adding-new-column-to-existing-dataframe-in-pandas/)

**Comment by patrickpato** [comment]
Thank you

**Comment by mikeatm** [comment]
try something like this:

```
ids = perovskites_df.task_id.values
fenergy=[];  gap=[]; dens=[] ; energy_p=[] ;  ratio=[]
for num,i in enumerate(ids):
    properties = m.query(criteria={'task_id': i}, properties=['final_energy', 'band_gap', 'density', 'energy_per_atom', 'poisson_ratio'])
    fenergy.append(properties[0]['final_energy'])
    gap.append( properties[0]['band_gap'])
    dens.append(properties[0]['density'])
    energy_p.append(properties[0]['energy_per_atom'])
    ratio.append(properties[0]['poisson_ratio'])
perovskites_df['final_energy'] = fenergy    
perovskites_df['band_gap'] = gap
perovskites_df['density'] = dens
perovskites_df['energy'] = energy_p
perovskites_df['poisson_ratio'] = ratio
perovskites_df.head()
```

**Comment by patrickpato** [comment]
thank you...let me try it out
